config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
 
  # {  for login }
  get "about", to: "about#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  
  resources :posts do
    resources :comments
  end

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "log_out", to: "sessions#destroy"

  root to: "main#index"

  # get "/students/:id", to: 'article#show'
  
  # get "/students", to: "student#index"

  # get '/students/:id', to: 'student#show' , as: 'student'

  # get '/students/:id/display', to: 'student#display'

  # get "/students/new", to: "student#new"
  

  # get 'articles', to: 'article#index'
  # post 'articles/cet', to: 'article#create'

  # resources :articles, path_names: { new: 'make',edit: 'change' }

  # resources :brands, only: [:index, :show] do
  #   resources :products, only: [:index, :show]
  # end



  # get '/profile', to: 'users#show' , as: 'temple_run'   * 'AS' is used to edit the helper path

  # resources :magazines do
  #   resources :ads, shallow: true
  # end
  # shallow do
  #   resources :articles do
  #     resources :comments
  #     resources :quotes
  #     resources :drafts
  #   end
  # end

  # concern :commentable do
  #   resources :comments
  # end
  # concern :image_attachable do
  #   resources :images, only: :index
  # end
  # resources :messages, concerns: :commentable
  # resources :articles, concerns: [:commentable, :image_attachable]
  
  # resources :photos do
  #     get 'preview', on: :collection
  # end
  

  # namespace :admin do
  #   resources :articles, :comments       * in this, url does follow the path admin in it like 
  # end                                    * /admin/articles/xyz 

  # scope module: 'admin' do
  #   resources :articles                   * in this, url does not follow the path admin 
  # end                                     * /artices/xyz

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :student
  validates :student_id, presence: true
  validates :title, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
   
  belongs_to :post
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates_associated :comments
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts
    validates :email, presence:true , format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create ,message:"invalid email input"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @user = User.find_by(id: session[:user_id])
  end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
    def index
        @articles = Article.all
    end
    
    def create
        @dn = params[:company]
        puts @dn
        debugger
    end

    def show

        # Rails.logger.debug params.inspect
        @student = Student.find(params[:id])
        # @articles = Article.find(params[:article_id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new()
  end
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id].to_i
    if @comment.save
      redirect_to post_path(params[:post_id].to_i), notice: "New Comment added"
    else
      render :new, alert: "something went wrong"
    end
  end
  def edit
    @comment = Comment.find(params[:id])
  end
  def update

    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(params[:post_id])
    else
      flash[:alert] = "Comment in not edited"
      redirect_to edit_post_comment_path
    end
  end
  def destroy
    @comment = Comment.find(params[:post_id])
    @comment.destroy
    redirect_to post_path(params[:id])

  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
  end
  def posts
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        if session[:user_id]
           @user = User.find_by(id: session[:user_id])
           @post = @user.posts
        else
            redirect_to :controller => 'posts', :action => 'post'
        end
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = session[:user_id]
        if @post.save
            redirect_to posts_path, notice: "New Post Added Succesfully"
        else
            flash[:alert] = "Something Went Wrong"
            redirect_to new_post_path
        end
    end

    def show
        @post = Post.find_by(id: params[:id])
        @comments = @post.comments
        
    end
    def edit
        @post = Post.find(params[:id])
        
    end
    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path
        else
            flash[:alert] = "Post in not edited"
            redirect_to edit_post_path
        end
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
   
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    def create
        user = User.find_by(email:params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to posts_path, notice: "logged in succesfully"
        else
            redirect_to sign_in_path, alert: "Invalid email or password"
        end
    end
    def destroy
        session.delete(:user_id)
        redirect_to root_path, notice: "Logged out" 
    end

end

app/controllers/student_controller.rb
class StudentController < ApplicationController

  # http_basic_authenticate_with name: "humbaba", password: "5baa61e4"

  # before_action :check_for_student


  def index

    cookies[:name] = Student.first.name
    # clients url = /student?status=activated

    # if params[:status] == "activated"
    #   @student = Student.last
    #   # redirect_to student_new_path
    # elsif params[:status] == "inactivated"
    #   @student = Student.first
    # else 
    #   @student = Student.first
    # end

    @students = Student.all
    # session[:name] = @student.name
    # session[:password] = @student.rollno

    # render json: @students


  end

  def new
    cookies.delete("name")
  end

  def show
    @student = Student.find(params[:id])

    # render json: @student

    # redirect_to action: :display

    # render layout: "display"

    # redirect_back(fallback_location: students_new_path)

  end

  def display
  end

  private
  def check_for_student
     puts "user has to loggin with the "
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/holders_helper.rb
module HoldersHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControllerPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
    <%= render partial: "shared/flash" %>
    <%= yield %>
    </div>
  </body>

</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
   <div class ="alert alert-info mt-4" role="alert"> 
    <%= flash[:notice] %>
   </div>
<% end %>
<% if flash[:alert] %>
    <div class ="alert alert-danger mt-4" role="alert"> 
       <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "FORM", root_path, class: "navbar-brand font" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "About", about_path, class: "nav-link" %>
        </li>
    
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>
      <li class="nav-item mt-2">
        <span class="navbar-text mt-5 pd-2 m-3"><%= Current.user.email %></span>
        </li>
        <li class="nav-item">
        <%= button_to "Logout", log_out_path, method: :delete,  class: "nav-link btn btn-secondary" %>      
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "SignUp", sign_up_path , class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "LogIn", sign_in_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>

    </div>
  </div>
</nav>