config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
 
  # {  for login }
  get "about", to: "about#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  
  resources :posts do
    resources :comments
  end

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "log_out", to: "sessions#destroy"

  root to: "main#index"

  # get "/students/:id", to: 'article#show'
  
  # get "/students", to: "student#index"

  # get '/students/:id', to: 'student#show' , as: 'student'

  # get '/students/:id/display', to: 'student#display'

  # get "/students/new", to: "student#new"
  

  # get 'articles', to: 'article#index'
  # post 'articles/cet', to: 'article#create'

  # resources :articles, path_names: { new: 'make',edit: 'change' }

  # resources :brands, only: [:index, :show] do
  #   resources :products, only: [:index, :show]
  # end



  # get '/profile', to: 'users#show' , as: 'temple_run'   * 'AS' is used to edit the helper path

  # resources :magazines do
  #   resources :ads, shallow: true
  # end
  # shallow do
  #   resources :articles do
  #     resources :comments
  #     resources :quotes
  #     resources :drafts
  #   end
  # end

  # concern :commentable do
  #   resources :comments
  # end
  # concern :image_attachable do
  #   resources :images, only: :index
  # end
  # resources :messages, concerns: :commentable
  # resources :articles, concerns: [:commentable, :image_attachable]
  
  # resources :photos do
  #     get 'preview', on: :collection
  # end
  

  # namespace :admin do
  #   resources :articles, :comments       * in this, url does follow the path admin in it like 
  # end                                    * /admin/articles/xyz 

  # scope module: 'admin' do
  #   resources :articles                   * in this, url does not follow the path admin 
  # end                                     * /artices/xyz

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates_associated :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        if session[:user_id]
           @user = User.find_by(id: session[:user_id])
           @post = @user.posts
        else
            redirect_to :controller => 'posts', :action => 'post'
        end
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = session[:user_id]
        if @post.save
            redirect_to posts_path, notice: "New Post Added Succesfully"
        else
            flash[:alert] = "Something Went Wrong"
            redirect_to new_post_path
        end
    end

    def show
        @post = Post.find_by(id: params[:id])
        @comments = @post.comments
        
    end
    def edit
        @post = Post.find(params[:id])
        
    end
    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path
        else
            flash[:alert] = "Post in not edited"
            redirect_to edit_post_path
        end
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
   
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :description)
    end
end

app/views/posts/edit.html.erb
<h1> Edit Form </h1>
<%= form_with model: @post, method: :put  do |form| %>
    <div class="mb-3">
    <%= form.label :titile %>
    <%= form.text_field :title, class: "form-control", placeholder: "title" %>
    </div>
    <div class="mb-3">
    <%= form.label :Description %>
    <%= form.text_field :description, class: "form-control", placeholder: "Description" %>
    </div>
    <div class="mb-3">
    <%= form.submit "Edit", class:"btn btn-primary" %>
    </div>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <% if Current.user %>
    <p class="p-4 m-4"><strong>User name : </strong> <%= Current.user.email %> </p> 
  <% end %>
  <%= button_to "Logout", log_out_path, method: :delete %>  
</div>
<div class="d-flex align-items-center justify-content-center">
  <p class="p-4 m-4"><strong>Add new Post</strong></p>
  <a class="btn btn-success" href="/posts/new" role="button">Add Post</a>
</div>

<div class="d-flex ">
<% @post.each do |pst| %>
    <div class="card p-3 m-3" style="width: 18rem;">
     <div class="card-body">
       <h4 class="card-title text-success">Post Id : <strong><%= pst.id %></strong></h4>
       <h5 class="card-title"><strong>Title : </strong><%= pst.title %></h5>
    
      <p class="card-text"><strong>Description : </strong><%= pst.description %></p>

      <a href="/posts/<%= pst.id %>" class="card-link">Details</a>
     </div>
    </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1> Add New Post </h1>
<%= form_with model: @post, url: posts_path  do |form| %>

    <div class="mb-3">
    <%= form.label :titile %>
    <%= form.text_field :title, class: "form-control", placeholder: "title" %>
    </div>
    <div class="mb-3">
    <%= form.label :Description %>
    <%= form.text_field :description, class: "form-control", placeholder: "Description" %>
    </div>
    <div class="mb-3">
    <%= form.submit "Create", class:"btn btn-primary" %>
     </div>
<% end %>

app/views/posts/show.html.erb
<h1 class="d-flex m-3 p-3 align-items-center justify-content-center">Post Details </h1>
<div class="card text-center">

  <h2 class="card-header">
    <strong>Title : </strong><%= @post.title %>
  </h2>
  <div class="card-body">
    <h3 class="card-text m-3 p-3"><strong> Description : </strong> <%= @post.description %></h3>
    <a href="<%= @post.id %>/edit" class="btn btn-primary m-4"> Edit </a>
    <%= link_to "Destroy", post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } , class:"btn btn-primary m-4" %>
    <a href="<%= @post.id %>/comments/new" class="btn btn-primary m-4"> Add Comment</a>
  </div>
  
  <div class="card-footer text-body-secondary">
  <h3>Comments : </h3>
  <div class="d-flex ">
  <% @comments.each do |comment| %>
    <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h6 class="card-title text-primary">Comment id : <%= comment.id %> </h6>
      <p class="card-text">: <%= comment.body %></p>
      <a href="/posts/<%= comment.post_id%>/comments/<%= comment.id%>/edit" class="card-link text-success">Edit</a>
      <%= link_to "Delete",post_comment_path(comment.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } , class:"card-link text-danger" %>
    </div>
   </div>
  <% end %>
  </div>
  </div>

</div>